config/routes.rb
Rails.application.routes.draw do
  get 'bars/index'

  get 'visitors/index'
  root 'visitors#index'
  get 'visitors/show'
  resources :visitors, only: [:index, :show]
  resources :reports do 
  	collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
	def self.import(file)
		CSV.foreach(file.path) do | row |
			emis, centre_no, sname, wrote_2014, passed_2014, wrote_2015, passed_2015, wrote_2016, passed_2016,
			 pass_rate, failure_rate, pass_rate2015, failure_rate2015, pass_rate2016, failure_rate2016 = row

			Report.create(emis: emis, centre_no: centre_no, school_name: sname,
			wrote_2014: wrote_2014, passed_2014: passed_2014, wrote_2015: wrote_2015,
			passed_2015: passed_2015, wrote_2016: wrote_2016, passed_2016: passed_2016,
			pass_rate: pass_rate,failure_rate: failure_rate, pass_rate2015: pass_rate2015, 
			failure_rate2015: failure_rate2015, pass_rate2016: pass_rate2016, failure_rate2016: failure_rate2016)
		end
	end

	def self.search(search)
  		if search
    		where(['emis ILIKE? OR school_name ILIKE?', "%#{search}%","%#{search}%"])
  		else
    		all
  		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def index
    @report = Report.find(56028)
    data_array_1 = [1]
  
    pass_rate = []
    pass_rate.push({:label => "2014", :value => @report.pass_rate.round(2)},{:label => "2015", :value => @report.pass_rate2015.round(2)},{:label => "2016", :value => @report.pass_rate2016.round(2)})

    @chart = Fusioncharts::Chart.new({
    :height => 400,
    :width => 600,
    :type => 'Column2D',
    :renderAt => 'chart-container',
    :dataSource => {
        :chart => {
            :size => '600x400',
            :caption => @report.school_name,
            :subCaption => 'Averege Rate For Each Year',
            :xAxisname => 'Year',
            :yAxisName => 'Percentage (%)',
            :numbersuffix => '%',
            :theme => 'fint',
            :yaxismaxvalue => "100",
            :dataFormat => 'json',
            placevaluesinside: "1",
            rotatevalues: "90",
            divlinealpha: "50",
            plotfillalpha: "80",
            drawCrossLine: "1",
            crossLineColor: "#cc3300",
            crossLineAlpha: "100",
            },
        :data => pass_rate
        }
    })

    failure_rate = []
    failure_rate.push({:label => "2014", :value => @report.failure_rate.round(2)},{:label => "2015", :value => @report.failure_rate2015.round(2)},{:label => "2016", :value => @report.failure_rate2016.round(2)})

    @charts = Fusioncharts::Chart.new({
    :height => 400,
    :width => 600,
    :type => 'pie3D',
    :renderAt => 'chartcontainer',
    :dataSource => {
        :chart => {
            :size => '600x400',
            :caption => 'School Failure Rate For Each Year',
            :xAxisname => 'Year',
            :yAxisName => 'Percentage (%)',
            :numbersuffix => '%',
            :theme => 'fint',
            :yaxismaxvalue => "100",
            :dataFormat => 'json',
            placevaluesinside: "1",
            rotatevalues: "0",
            divlinealpha: "50",
            plotfillalpha: "80",
            drawCrossLine: "1",
            crossLineColor: "#cc3300",
            crossLineAlpha: "100",
            },
        :data => failure_rate
        }
    })

  	
  
	data_array_2 = [4, 2, 10, 4, 7, 4]

	@bar = Gchart.bar(
            :renderAt => 'ccontainer',
           
            :bar_colors => ['000000', '0088FF'],
            :title => "My Title",
            :bg => 'EFEFEF',
            :legend => ['first data set label', 'second data set label'],
            :data => [data_array_1],
            :filename => 'images/bar_chart.png',
            :stacked => false,
            :legend_position => 'bottom',
            :axis_with_labels => [['x'], ['y']],
            :max_value => 15,
            :min_value => 0,
            :axis_labels => [["A|B|C|D|E"]],
            )
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import 
    Report.import(params[:file])
    redirect_to reports_path, notice: "Report added"
  rescue 
    reports_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:emis, :centre_no, :school_name, :wrote_2014, :passed_2014, :wrote_2015, :passed_2015, :wrote_2016, :passed_2016, :pass_rate, :failure_rate, :pass_rate2015, :failure_rate2015, :pass_rate2016, :failure_rate2016)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  	@reports = Report.search(params[:search])
  end

  def show
  	@report = Report.find(params[:id])
   failure_rate = []
    failure_rate.push({:label => "2014", :value => @report.failure_rate.round(2)},{:label => "2015", :value => @report.failure_rate2015.round(2)},{:label => "2016", :value => @report.failure_rate2016.round(2)})

    @chart = Fusioncharts::Chart.new({
    :height => 400,
    :width => 600,
    :type => 'Column2D',
    :renderAt => 'chart-container',
    :dataSource => {
        :chart => {
            :caption => 'Top 10 Most Populous City in selected Country',
            :xAxisname => 'Quarter',
            :yAxisName => 'Amount (%)',
            :numbersuffix => '%',
            :theme => 'fint',
            :yaxismaxvalue => "100",
            :dataFormat => 'json',
            placevaluesinside: "1",
            rotatevalues: "0",
            divlinealpha: "50",
            plotfillalpha: "80",
            drawCrossLine: "1",
            crossLineColor: "#cc3300",
            crossLineAlpha: "100",
            },
        :data => failure_rate
        }
    })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/bars/index.html.erb
<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Year', 'Pass Rate', 'Failure rate', 'Profit'],
          ['2014', <%= @report.pass_rate.round(2) %>, <%= @report.failure_rate %>, <%= @report.pass_rate2016 %>],
          ['2015', <%= @report.pass_rate2015 %>, <%= @report.failure_rate2015 %>, <%= @report.pass_rate2016 %>],
          ['2016', <%= @report.pass_rate2016 %>, <%= @report.failure_rate2016 %>, <%= @report.pass_rate2016 %>]
         
        ]);

        var options = {
          chart: {
          	isStacked: 'percent',
          	bg: '000000',
            title: '<%= @report.school_name %>',
            subtitle: 'Sales, Expenses, and Profit: 2014-2017',
          },
           vAxis: {
          title: 'Total Population',
          minValue: 0,
          maxValue: 100,
          format:'#,##%'
        },
        hAxis: {
          title: 'City'
        },
          bars: 'vertical' // Required for Material Bar Charts.
        };

        var chart = new google.charts.Bar(document.getElementById('barchart_material'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
      }
    </script>
  </head>
  <body>
    <div id="barchart_material" style="width: 900px; height: 500px;"></div>
    <h1>Bars#index</h1>
<p>Find me in app/views/bars/index.html.erb</p>

<div id="ccontainer" class="container"><%= image_tag @bar %></div>

<div class="container col-md-12">
	<div class="row">
		<h3>My Chart</h3>
		<div id="chartcontainer" class="col-md-6"><%= @charts.render() %></div>
		<div id="chart-container" class="col-md-6"><%= @chart.render() %></div>
		
	</div>
</div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatricReport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 <div class="bs-example">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand">Matric report</a>
        </div>
        <div id="navbarCollapse" class="collapse navbar-collapse">
       
          <%= form_tag visitors_path, method: 'get',class: "navbar-form navbar-left" do %>
          <%= text_field_tag :search, params[:search], class: "form-control" %>

          <%= submit_tag "Search" ,class: "btn btn-default"%>
  
        <% end %>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">Login</a></li>
            </ul>
        </div>
    </nav>
  </div>
  
  <body>
  	<div class="container">
  		<%= yield %>
  	</div>
  </body>
</html>

app/views/reports/_form.html.erb
<%= form_with(model: report, local: true) do |form| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :emis %>
    <%= form.text_field :emis, id: :report_emis %>
  </div>

  <div class="field">
    <%= form.label :centre_no %>
    <%= form.text_field :centre_no, id: :report_centre_no %>
  </div>

  <div class="field">
    <%= form.label :school_name %>
    <%= form.text_field :school_name, id: :report_school_name %>
  </div>

  <div class="field">
    <%= form.label :wrote_2014 %>
    <%= form.number_field :wrote_2014, id: :report_wrote_2014 %>
  </div>

  <div class="field">
    <%= form.label :passed_2014 %>
    <%= form.number_field :passed_2014, id: :report_passed_2014 %>
  </div>

  <div class="field">
    <%= form.label :wrote_2015 %>
    <%= form.number_field :wrote_2015, id: :report_wrote_2015 %>
  </div>

  <div class="field">
    <%= form.label :passed_2015 %>
    <%= form.number_field :passed_2015, id: :report_passed_2015 %>
  </div>

  <div class="field">
    <%= form.label :wrote_2016 %>
    <%= form.number_field :wrote_2016, id: :report_wrote_2016 %>
  </div>

  <div class="field">
    <%= form.label :passed_2016 %>
    <%= form.number_field :passed_2016, id: :report_passed_2016 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Import file</h3>

<%= form_tag import_reports_path, multipart: true, class: "form-inline my-2 my-lg-0" do %>
 <%= file_field_tag :file, class: "form-control mr-sm-2" %>
 <%= submit_tag "Upload report" ,class: "btn btn-outline-success my-2 my-sm-0"%>
 <% end %>

<h1>Reports</h1>

<table class = "table">
  <thead class = "thead-dark">
    <tr>
      <th>Emis</th>
      <th>Centre no</th>
      <th>School name</th>
      <th>Wrote 2014</th>
      <th>Passed 2014</th>
      <th>Wrote 2015</th>
      <th>Passed 2015</th>
      <th>Wrote 2016</th>
      <th>Passed 2016</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.emis %></td>
        <td><%= report.centre_no %></td>
        <td><%= report.school_name %></td>
        <td><%= report.wrote_2014 %></td>
        <td><%= report.passed_2014 %></td>
        <td><%= report.wrote_2015 %></td>
        <td><%= report.passed_2015 %></td>
        <td><%= report.wrote_2016 %></td>
        <td><%= report.passed_2016 %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emis:</strong>
  <%= @report.emis %>
</p>

<p>
  <strong>Centre no:</strong>
  <%= @report.centre_no %>
</p>

<p>
  <strong>School name:</strong>
  <%= @report.school_name %>
</p>

<p>
  <strong>Wrote 2014:</strong>
  <%= @report.wrote_2014 %>
</p>

<p>
  <strong>Passed 2014:</strong>
  <%= @report.passed_2014 %>
</p>

<p>
  <strong>Wrote 2015:</strong>
  <%= @report.wrote_2015 %>
</p>

<p>
  <strong>Passed 2015:</strong>
  <%= @report.passed_2015 %>
</p>

<p>
  <strong>Wrote 2016:</strong>
  <%= @report.wrote_2016 %>
</p>

<p>
  <strong>Passed 2016:</strong>
  <%= @report.passed_2016 %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

app/views/visitors/index.html.erb
<h1>Reports</h1>

<table class = "table">
  <thead class="thead-dark">
    <tr>
      <th>Emis</th>
      <th>Centre no</th>
      <th>School name</th>
      <th>Wrote 2014</th>
      <th>Passed 2014</th>
      <th>Wrote 2015</th>
      <th>Passed 2015</th>
      <th>Wrote 2016</th>
      <th>Passed 2016</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr class = "table-striped">
        <td><%= report.emis %></td>
        <td><%= report.centre_no %></td>
        <td><%= report.school_name %></td>
        <td><%= report.wrote_2014 %></td>
        <td><%= report.passed_2014 %></td>
        <td><%= report.wrote_2015 %></td>
        <td><%= report.passed_2015 %></td>
        <td><%= report.wrote_2016 %></td>
        <td><%= report.passed_2016 %></td>
        <td><%= link_to 'Show', visitor_url(report) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/visitors/show.html.erb
 
<html>
  <head>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  
  </head>
  <body>
    <td><%= link_to 'Please refresh here if there is no graph', visitor_url(@report), class: "btn" %></td>
      
      <script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Year', 'Pass Rate', 'Failure rate'],
          ['2014', <%= @report.pass_rate.round(2) %>, <%= @report.failure_rate %>],
          ['2015', <%= @report.pass_rate2015 %>, <%= @report.failure_rate2015 %>],
          ['2016', <%= @report.pass_rate2016 %>, <%= @report.failure_rate2016 %>]
         
        ]);

        var options = {

          chart: {
            bg: '000000',
            title: '<%= @report.school_name %>',
            subtitle: 'Report analyser',
            align: "center"
          },
           vAxis: {
          title: 'Percentage (%)',
          minValue: 0,
          maxValue: 100,
          format:'#,##%'
        },
        hAxis: {
          title: 'Year'
        },

          bars: 'vertical' // Required for Material Bar Charts.
        };

        var chart = new google.charts.Bar(document.getElementById('barchart_material'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
      }
    </script>
<div class="container">
  <div class="row">
      <div id="barchart_material" style="width: 900px; height: 500px;" class="col-sm-6 col-md-3">
     </div>
  </div>
</div>
<div class="container">
   <div class="row">
  <p class="col-sm-6 col-md-3">
  <strong>YEAR</strong>
</p>
  <p class="col-sm-6 col-md-3">
  <strong>SCHOOL</strong>
</p>
<p class="col-sm-6 col-md-3">
  <strong>NUMBER WROTE</strong>
</p>
<p class="col-sm-6 col-md-3">

  <strong>NUMBER PASSED</strong>
</p>
</div>
  <div class="row">
    <p class="col-sm-6 col-md-3">
  <strong>2014</strong>
</p>
  <p class="col-sm-6 col-md-3">
  <strong><%= @report.school_name %></strong>
</p>
<p class="col-sm-6 col-md-3">
 
  <strong><%= @report.wrote_2014 %></strong>
   Wrote exams
</p>
<p class="col-sm-6 col-md-3">
   Only
  <strong><%= @report.passed_2014 %></strong>
   passed exams
</p>

</div>
 <div class="row">
  <p class="col-sm-6 col-md-3">
  <strong>2015</strong>
</p>
  <p class="col-sm-6 col-md-3">
  <strong><%= @report.school_name %></strong>
</p>
<p class="col-sm-6 col-md-3">
 
  <strong><%= @report.wrote_2015 %></strong>
   Wrote exams
</p>
<p class="col-sm-6 col-md-3">
   Only
  <strong><%= @report.passed_2015 %></strong>
   passed exams
</p>

</div>
 <div class="row">
  <p class="col-sm-6 col-md-3">
  <strong>2016</strong>
</p>
  <p class="col-sm-6 col-md-3">
  <strong><%= @report.school_name %></strong>
</p>
<p class="col-sm-6 col-md-3">
 
  <strong><%= @report.wrote_2016 %></strong>
   Wrote exams
</p>
<p class="col-sm-6 col-md-3">
   Only
  <strong><%= @report.passed_2016 %></strong>
   passed exams
</p>
</div>
</div>
  </body>
</html>